version : "3.9"
services :
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
volumes :
  dev-db-data: